### ISSUE TITLE
TcpEndpoint.kt:19-21: Create an object that can format...

### ISSUE THREAD

**Issue by 0pdd** [kerelape/reikai#7]
The puzzle `2-c32df101` from #2 has to be resolved: 

https://github.com/kerelape/reikai/blob/a4ea7f8cc2f9ec4cc99dd99ab225c96646a43735/src/main/kotlin/me/kerelape/reikai/io/network/TcpEndpoint.kt#L19-L21

The puzzle was created by Киряев Кирилл on 20-Jul-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Masynchin** [comment]
@kerelape since Text is introduced, this can be solved. As I just have read [here](https://stackoverflow.com/questions/23086291/format-in-kotlin-string-templates), Kotlin has format strings. Can we use it for Sprintf? Implementation would be something like:

```kotlin
Sprintf(origin: Entity, ...args: Entity) {
    dataize() { Text(String(origin).format(..args)) }
}
```

I use `origin: Entity` because `This object must accept a` ~~`quantum`~~`entity of text`. Am I right?

**Comment by kerelape** [comment]
@Masynchin implement it. But since Kotlin cannot understand of what type that `Entity` is, it'll call the `toString` methods, which are going to return address of the object in the memory in most cases. So for now simply treat every arg as an `Entity` of text (and don't forget to mention in the doc)

**Comment by 0pdd** [comment]
The puzzle `2-c32df101` has disappeared from the source code, that's why I closed this issue.
